---
- name: Nextcloud
  hosts: nextcloud

  tasks:
    - name: Timezone Moscow
      community.general.timezone:
        name: Europe/Moscow

    - name: Update sw
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
          - acl
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-zip
          - php-intl
          - php-mysql
          - php-pgsql
          - php-bcmath
          - unzip
          - python3-pip
          - postgresql-all
          - wget
          - bzip2
        state: present

    - name: Install psycopg2
      ansible.builtin.pip:
        extra_args: "--break-system-packages"
        name: psycopg2

    - name: Install Nextcloud
      ansible.builtin.unarchive:
        dest: "/var/www/html"
        src: "https://download.nextcloud.com/server/releases/latest-30.tar.bz2"
        remote_src: true
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"

    - name: Init PostgreSQL user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: pguser
        password: pgpassword

    - name: Init PostgreSQL DB for Nextcloud
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: dbnextcloud
        owner: pguser